# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856324b1617d2f2ce1e98237905efdc6b981410a566fedaf08b5025b46d86788e40989260642692a8cc6aab3ae1cc9f41582aae9f94dcfa85b79acabf06c2285

test:
  secret_key_base: 1e897e72f3da0d6224cd1d6f3b66129a0ddd5dbcde9d7495a5233f98853b42503c0b17ddd7c389f66c2b9543af3e95c30acb2b849c9ae9f8f89c033c12f5a051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
